#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Nov  1 21:17:10 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class PhotoControl(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PhotoControl.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.window_1 = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_1_pane_2 = wx.ScrolledWindow(self.window_1, -1, style=wx.DOUBLE_BORDER|wx.TAB_TRAVERSAL)
        self.window_1_pane_1 = wx.Panel(self.window_1, -1)
        
        # Menu Bar
        self.frame_3_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Read Configuration", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "Save Configuration", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "Quit", "", wx.ITEM_NORMAL)
        self.frame_3_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Initialize Capture", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "Run Capture ", "", wx.ITEM_NORMAL)
        self.frame_3_menubar.Append(wxglade_tmp_menu, "Capture")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "About", "", wx.ITEM_NORMAL)
        self.frame_3_menubar.Append(wxglade_tmp_menu, "Help")
        self.SetMenuBar(self.frame_3_menubar)
        # Menu Bar end
        self.frame_3_statusbar = self.CreateStatusBar(5, 0)
        self.label_1 = wx.StaticText(self.window_1_pane_1, -1, "Control Panel\n")
        self.button_1 = wx.Button(self.window_1_pane_1, -1, "Initialize Camera")
        self.label_2 = wx.StaticText(self.window_1_pane_1, -1, "Number of Shots")
        self.numshots = wx.SpinCtrl(self.window_1_pane_1, -1, "1000", min=0, max=5000)
        self.label_3 = wx.StaticText(self.window_1_pane_1, -1, "Interval (senconds)")
        self.spin_ctrl_1 = wx.SpinCtrl(self.window_1_pane_1, -1, "", min=0, max=300)
        self.bitmap_1 = wx.StaticBitmap(self.window_1_pane_2, -1, wx.Bitmap("/home/alex/r-files/PhotoControl/backdefault.jpg", wx.BITMAP_TYPE_ANY))
        self.log_area = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_LINEWRAP)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PhotoControl.__set_properties
        self.SetTitle("mainframe")
        self.SetSize((961, 710))
        self.frame_3_statusbar.SetStatusWidths([400, 200, 50, 50, -1])
        # statusbar fields
        frame_3_statusbar_fields = ["statusbarinfo", "statusbar_camera", "statusbar_run", "statusbar_total", "statusbar_eta"]
        for i in range(len(frame_3_statusbar_fields)):
            self.frame_3_statusbar.SetStatusText(frame_3_statusbar_fields[i], i)
        self.window_1_pane_2.SetScrollRate(10, 10)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PhotoControl.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.GridSizer(1, 1, 0, 0)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.label_1, 0, wx.EXPAND, 0)
        sizer_3.Add(self.button_1, 0, wx.ALL|wx.EXPAND, 0)
        sizer_3.Add(self.label_2, 0, 0, 0)
        sizer_3.Add(self.numshots, 0, wx.EXPAND, 0)
        sizer_3.Add(self.label_3, 0, wx.EXPAND, 0)
        sizer_3.Add(self.spin_ctrl_1, 0, wx.EXPAND, 0)
        self.window_1_pane_1.SetSizer(sizer_3)
        sizer_4.Add(self.bitmap_1, 1, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT, 0)
        self.window_1_pane_2.SetSizer(sizer_4)
        self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)
        sizer_2.Add(self.window_1, 1, wx.EXPAND, 2)
        sizer_2.Add(self.log_area, 1, wx.EXPAND, 1)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

# end of class PhotoControl


if __name__ == "__main__":
    PhotoControll = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    mainframe = PhotoControl(None, -1, "")
    PhotoControll.SetTopWindow(mainframe)
    mainframe.Show()
    PhotoControll.MainLoop()
